FROM golang:1-alpine AS build

RUN apk add git && \
    CGO_ENABLED=0 go get -v github.com/jpillora/cloud-torrent

RUN mkdir -p /rootfs/etc && \
    cp /go/bin/cloud-torrent /rootfs/ && \
    echo "nogroup:*:100:nobody" > /rootfs/etc/group && \
    echo "nobody:*:100:100:::" > /rootfs/etc/passwd && \
    mkdir -p /rootfs/downloads


FROM scratch

COPY --from=build --chown=100:100 /rootfs /

USER 100:100
VOLUME ["/downloads"]
EXPOSE 3000/tcp
ENTRYPOINT ["/cloud-torrent"]
